---
'^-^': ''
':d': ''
'-_-': ''

'o_o': ''
# '^-^o': ''
'>_<': ''
'.-.': ''
':in_love': ''
':kissing': ''
':tongue': ''

':c': ''
':sad': ''
':brr': ''
':cry': ''
':angry': ''
'*-^': ''
'*_^': ''

':evil': ''
':clown': ''
':poop': ''
':skull': ''
':happy': ''
':broken_heart': ''
':heart': ''
':pumpkin': ''
':frozen': ''
':alien': ''
':yellow_heart': ''
':orange_heart': ''
':green_heart': ''
':purple_heart': ''
':blue_heart': ''

':eyes': ''

':triggered': ''
':lol': ''
':mounth': ''
':my_deal': ''
...
