---
# bossbar: Bossbar Management
bossbar:
  title: '>> BLOOMLAND - Игровой сервер 1.18 <<'
  percentage: 1

# scoreboard: Scoreboard Management
scoreboard:
  title: 'Bloom!'
  lines:
    - 'Whats up?'
    - 'How are you?'

# messages: Array with information messages 
messages:
  - 'Информационное сообщение: 1'
  - 'Информационное сообщение: 2'
  - 'Информационное сообщение: 3'

# kitItems: Array with items for the starter kit
kitItems:
  - [272, 0, 1]
  - [274, 0, 1]
  - [275, 0, 1]
  - [260, 0, 8]
  - [401, 0, 16]

# blocked-commands: An array of limited commands
blocked-commands:
  op:
    console: false
    in-game: true
...