---
scoreboard:
  title: 'Bloom!'
  lines:
    - 'Whats up?'
    - 'How are you?'
messages:
  - 'Информационное сообщение: 1'
  - 'Информационное сообщение: 2'
  - 'Информационное сообщение: 3'
blocked-commands:
  op:
    console: false
    in-game: true
...