---
bossbar:
  title: '>> BLOOMLAND - Игровой сервер 1.18 <<'
  percentage: 1
scoreboard:
  title: 'Bloom!'
  lines:
    - 'Whats up?'
    - 'How are you?'
messages:
  - 'Информационное сообщение: 1'
  - 'Информационное сообщение: 2'
  - 'Информационное сообщение: 3'
kitItems:
  - [272, 0, 1]
  - [274, 0, 1]
  - [275, 0, 1]
  - [260, 0, 8]
  - [401, 0, 16]
blocked-commands:
  op:
    console: false
    in-game: true
...